# Generated by Django 5.2.4 on 2025-12-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributodinamico',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Atributo Dinámico', 'verbose_name_plural': 'Atributos Dinámicos'},
        ),
        migrations.AddField(
            model_name='atributodinamico',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='atributodinamico',
            name='tipo_producto',
            field=models.CharField(choices=[('general', 'General (Todos)'), ('electrica', 'Motos Eléctricas'), ('combustion', 'Motos de Combustión'), ('triciclo', 'Triciclos')], default='general', help_text='A qué tipo de producto aplica este atributo', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='atributodinamico',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Atributo'),
        ),
        migrations.AlterField(
            model_name='atributodinamico',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Ej. W, cc, V, Ah, km/h, km, L', max_length=20, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterUniqueTogether(
            name='atributodinamico',
            unique_together={('nombre', 'tipo_producto')},
        ),
    ]
