# Generated by Django 5.2.4 on 2025-12-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_atributodinamico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Color')),
                ('codigo_hex', models.CharField(help_text='Ej: #FF0000 para rojo', max_length=7, verbose_name='Código Hexadecimal')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='atributodinamico',
            options={'ordering': ['tipo_producto', 'orden', 'nombre'], 'verbose_name': 'Atributo Dinámico', 'verbose_name_plural': 'Atributos Dinámicos'},
        ),
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden', 'fecha_subida'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Productos'},
        ),
        migrations.AlterModelOptions(
            name='valorproducto',
            options={'verbose_name': 'Valor de Atributo', 'verbose_name_plural': 'Valores de Atributos'},
        ),
        migrations.RemoveField(
            model_name='valorproducto',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='atributodinamico',
            name='tipo_producto',
            field=models.CharField(choices=[('general', 'General (Todos)'), ('electrica', 'Motos Eléctricas'), ('combustion', 'Motos de Combustión'), ('triciclo', 'Triciclos')], default='general', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='atributodinamico',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Ej: km, W, cc, L', max_length=20, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares USD'), ('EUR', 'Euros'), ('CUP', 'Pesos Cubanos'), ('MLC', 'Moneda Libremente Convertible')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU (Código de Producto)'),
        ),
        migrations.AlterField(
            model_name='valorproducto',
            name='valor',
            field=models.CharField(max_length=200, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(blank=True, related_name='productos', to='productos.color', verbose_name='Colores Disponibles'),
        ),
    ]
