# Generated by Django 5.2.4 on 2026-01-09 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_color_alter_atributodinamico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unidades Vendidas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vistas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Vistas'),
        ),
    ]
