# Generated by Django 5.2.7 on 2026-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_ventas_producto_vistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_hero', models.ImageField(upload_to='home/', verbose_name='Imagen del Hero Section')),
                ('texto_badge', models.CharField(blank=True, default='Modelo 2025', max_length=50, verbose_name='Texto del badge')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración Home',
                'verbose_name_plural': 'Configuración Home',
            },
        ),
    ]
