# Generated by Django 5.2.7 on 2026-03-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_configuracionhome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributodinamico',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Atributo Dinámico', 'verbose_name_plural': 'Atributos Dinámicos'},
        ),
        migrations.AlterUniqueTogether(
            name='atributodinamico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='atributodinamico',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Dejar vacío para que aplique a todos los productos', related_name='atributos', to='productos.categoria', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='atributodinamico',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Atributo'),
        ),
        migrations.RemoveField(
            model_name='atributodinamico',
            name='tipo_producto',
        ),
    ]
